In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("t20i_info.csv")

In [3]:
df.head()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,0,2,Australia,Sri Lanka,0.1,0,0,NaN,Melbourne Cricket Ground
1,1,2,Australia,Sri Lanka,0.2,0,0,NaN,Melbourne Cricket Ground
2,2,2,Australia,Sri Lanka,0.3,1,0,NaN,Melbourne Cricket Ground
3,3,2,Australia,Sri Lanka,0.4,2,0,NaN,Melbourne Cricket Ground
4,4,2,Australia,Sri Lanka,0.5,0,0,NaN,Melbourne Cricket Ground

In [4]:
df.isnull().sum()

Unnamed: 0             0
match_id               0
batting_team           0
bowling_team           0
ball                   0
runs                   0
player_dismissed       0
city                8548
venue                  0
dtype: int64

In [5]:
df.shape

(63888, 9)

In [6]:
# Cricbuzz, Cricket Line Guru, Tv Screen -> Projected Score / Predicted Score

batting team,
bowling team,
city,
current score,
balls left,
wicket left,
current run rate,
last five/six->powerplay,

In [7]:
df[df['city'].isnull()]['venue'][0].split(" ")[0]

'Melbourne'

In [8]:
df['city'] = df['city'].fillna(df['venue'].apply(lambda x: x.split(' ')[0]))

In [9]:
df.tail()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium
63885,123,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium

In [10]:
df.isnull().sum()

Unnamed: 0          0
match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [11]:
df['city'].value_counts()

city
Colombo          4086
Mirpur           3420
Johannesburg     3331
Dubai            2969
Auckland         2532
                 ...
Victoria          123
Potchefstroom     122
Dharamsala        122
Ahmedabad         121
Carrara            64
Name: count, Length: 86, dtype: int64

In [12]:
eligible_cites = df['city'].value_counts()[df['city'].value_counts() > 600].index.tolist()

In [13]:
eligible_cites

['Colombo',
 'Mirpur',
 'Johannesburg',
 'Dubai',
 'Auckland',
 'Cape Town',
 'London',
 'Pallekele',
 'Barbados',
 'Sydney',
 'Melbourne',
 'Durban',
 'St Lucia',
 'Wellington',
 'Lauderhill',
 'Hamilton',
 'Centurion',
 'Manchester',
 'Abu Dhabi',
 'Mumbai',
 'Nottingham',
 'Southampton',
 'Mount Maunganui',
 'Chittagong',
 'Kolkata',
 'Lahore',
 'Delhi',
 'Nagpur',
 'Chandigarh',
 'Adelaide',
 'Bangalore',
 'St Kitts',
 'Cardiff',
 'Christchurch',
 'Trinidad']

In [14]:
df = df[df['city'].isin(eligible_cites)]

In [15]:
df.shape

(50501, 9)

In [16]:
df

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground
1,1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground
2,2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground
3,3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground
4,4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...,...
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium
63885,123,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium

In [ ]:
df.head()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current_score
0,0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground,0
1,1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground,0
2,2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground,1
3,3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground,3
4,4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,3

In [18]:
df['over'] = df['ball'].apply(lambda x : str(x).split(".")[0])
df['ball_no'] = df['ball'].apply(lambda x : str(x).split(".")[1])

In [19]:
df.head()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,over,ball_no
0,0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground,0,1
1,1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground,0,2
2,2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground,0,3
3,3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground,0,4
4,4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,0,5

In [20]:
df['ball_bowled'] = (df['over'].astype(int)*6 + df['ball_no'].astype(int))

In [21]:
df.tail()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,over,ball_no,ball_bowled
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,19,3,117
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,19,4,118
63885,123,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium,19,5,119
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,19,6,120
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,19,7,121

In [22]:
df['balls_left'] = 120 - df['ball_bowled']

In [23]:
df.tail()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,over,ball_no,ball_bowled,balls_left
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,19,3,117,3
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,19,4,118,2
63885,123,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium,19,5,119,1
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,19,6,120,0
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,19,7,121,-1

In [24]:
df['balls_left'] = df['balls_left'].apply(lambda x:0 if x<0 else x)

In [25]:
df.tail()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,over,ball_no,ball_bowled,balls_left
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,19,3,117,3
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,19,4,118,2
63885,123,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium,19,5,119,1
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,19,6,120,0
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,19,7,121,0

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50501 entries, 0 to 63887
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        50501 non-null  int64
 1   match_id          50501 non-null  int64
 2   batting_team      50501 non-null  object
 3   bowling_team      50501 non-null  object
 4   ball              50501 non-null  float64
 5   runs              50501 non-null  int64
 6   player_dismissed  50501 non-null  object
 7   city              50501 non-null  object
 8   venue             50501 non-null  object
 9   over              50501 non-null  object
 10  ball_no           50501 non-null  object
 11  ball_bowled       50501 non-null  int64
 12  balls_left        50501 non-null  int64
dtypes: float64(1), int64(5), object(7)
memory usage: 5.4+ MB

In [27]:
df['player_dismissed'] = df['player_dismissed'].apply(lambda x:1 if x!='0' else '0')

In [28]:
df

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,over,ball_no,ball_bowled,balls_left
0,0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground,0,1,1,119
1,1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground,0,2,2,118
2,2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground,0,3,3,117
3,3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground,0,4,4,116
4,4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,19,3,117,3
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,19,4,118,2
63885,123,964,Sri Lanka,Australia,19.5,0,1,Colombo,R Premadasa Stadium,19,5,119,1
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,19,6,120,0
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,19,7,121,0

In [29]:
df['player_dismissed'] = df['player_dismissed'].astype(int)

In [32]:
df['player_dismissed_flag'] = df['player_dismissed'].notnull().astype(int)
df['cumulative_dismissals'] = df.groupby('match_id')['player_dismissed_flag'].cumsum()

In [33]:
df['wicket_left'] = 10 - df['player_dismissed']

In [34]:
df.tail()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,over,ball_no,ball_bowled,balls_left,player_dismissed_flag,cumulative_dismissals,wicket_left
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,19,3,117,3,1,122,10
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,19,4,118,2,1,123,10
63885,123,964,Sri Lanka,Australia,19.5,0,1,Colombo,R Premadasa Stadium,19,5,119,1,1,124,9
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,19,6,120,0,1,125,10
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,19,7,121,0,1,126,10

In [40]:
print(df.columns.tolist())

['Unnamed: 0', 'match_id', 'batting_team', 'bowling_team', 'ball', 'runs', 'player_dismissed', 'city', 'venue', 'over', 'ball_no', 'ball_bowled', 'balls_left', 'player_dismissed_flag', 'cumulative_dismissals', 'wicket_left']

In [41]:
df['current_score'] = df.groupby('match_id')['runs'].cumsum()

In [42]:
df.tail()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,over,ball_no,ball_bowled,balls_left,player_dismissed_flag,cumulative_dismissals,wicket_left,current_score
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,19,3,117,3,1,122,10,125
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,19,4,118,2,1,123,10,125
63885,123,964,Sri Lanka,Australia,19.5,0,1,Colombo,R Premadasa Stadium,19,5,119,1,1,124,9,125
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,19,6,120,0,1,125,10,127
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,19,7,121,0,1,126,10,128

In [50]:
print(df.columns)

Index(['Unnamed: 0', 'match_id', 'batting_team', 'bowling_team', 'ball',
       'runs', 'player_dismissed', 'city', 'venue', 'over', 'ball_no',
       'ball_bowled', 'balls_left', 'player_dismissed_flag',
       'cumulative_dismissals', 'wicket_left', 'current_score'],
      dtype='object')

In [56]:
# Convert 'current_score' column to numeric
df['current_score'] = pd.to_numeric(df['current_score'], errors='coerce')

In [57]:
if 'current_score' in df.columns:
    df['current_score'] = pd.to_numeric(df['current_score'], errors='coerce')
else:
    print("The 'score' column does not exist.")

In [59]:
print(df['current_score'].isna().sum())

0

In [60]:
df = df.dropna(subset=['current_score'])

In [61]:
df['current_score'] = df['current_score'].fillna(0)

In [62]:
# Apply the rolling window operation (e.g., calculating a rolling mean)
rolling_mean = df['current_score'].rolling(window=2).mean()

# Output the rolling mean
print(rolling_mean)

0          NaN
1          0.0
2          0.5
3          2.0
4          3.0
         ...
63883    124.5
63884    125.0
63885    125.0
63886    126.0
63887    127.5
Name: current_score, Length: 50501, dtype: float64

In [69]:
df['last_five'] = df['runs'].rolling(window=5).sum()

In [71]:
print(df.head())  # Display the first few rows of the DataFrame

   Unnamed: 0  match_id batting_team bowling_team  ball  runs  \
0           0         2    Australia    Sri Lanka   0.1     0
1           1         2    Australia    Sri Lanka   0.2     0
2           2         2    Australia    Sri Lanka   0.3     1
3           3         2    Australia    Sri Lanka   0.4     2
4           4         2    Australia    Sri Lanka   0.5     0

   player_dismissed       city                     venue over ball_no  \
0                 0  Melbourne  Melbourne Cricket Ground    0       1
1                 0  Melbourne  Melbourne Cricket Ground    0       2
2                 0  Melbourne  Melbourne Cricket Ground    0       3
3                 0  Melbourne  Melbourne Cricket Ground    0       4
4                 0  Melbourne  Melbourne Cricket Ground    0       5

   ball_bowled  balls_left  player_dismissed_flag  cumulative_dismissals  \
0            1         119                      1                      1
1            2         118                      1                      2
2            3         117                      1                      3
3            4         116                      1                      4
4            5         115                      1                      5

   wicket_left  current_score  last_five
0           10              0        NaN
1           10              0        NaN
2           10              1        NaN
3           10              3        NaN
4           10              3        3.0

In [72]:
df = df.dropna(subset=['last_five'])

In [74]:
df['last_five'] = df['last_five'].fillna(0)

C:\Users\SANTHU\AppData\Local\Temp\ipykernel_2452\1266062430.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['last_five'] = df['last_five'].fillna(0)

In [75]:
df.head()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,over,ball_no,ball_bowled,balls_left,player_dismissed_flag,cumulative_dismissals,wicket_left,current_score,last_five
4,4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,0,5,5,115,1,5,10,3,3.0
5,5,2,Australia,Sri Lanka,0.6,3,0,Melbourne,Melbourne Cricket Ground,0,6,6,114,1,6,10,6,6.0
6,6,2,Australia,Sri Lanka,1.1,0,0,Melbourne,Melbourne Cricket Ground,1,1,7,113,1,7,10,6,6.0
7,7,2,Australia,Sri Lanka,1.2,1,0,Melbourne,Melbourne Cricket Ground,1,2,8,112,1,8,10,7,6.0
8,8,2,Australia,Sri Lanka,1.3,0,0,Melbourne,Melbourne Cricket Ground,1,3,9,111,1,9,10,7,4.0

In [76]:
final_df = df.groupby('match_id').sum()['runs'].reset_index().merge(df, on='match_id')

In [77]:
final_df

,match_id,runs_x,Unnamed: 0,batting_team,bowling_team,ball,runs_y,player_dismissed,city,venue,over,ball_no,ball_bowled,balls_left,player_dismissed_flag,cumulative_dismissals,wicket_left,current_score,last_five
0,2,165,4,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,0,5,5,115,1,5,10,3,3.0
1,2,165,5,Australia,Sri Lanka,0.6,3,0,Melbourne,Melbourne Cricket Ground,0,6,6,114,1,6,10,6,6.0
2,2,165,6,Australia,Sri Lanka,1.1,0,0,Melbourne,Melbourne Cricket Ground,1,1,7,113,1,7,10,6,6.0
3,2,165,7,Australia,Sri Lanka,1.2,1,0,Melbourne,Melbourne Cricket Ground,1,2,8,112,1,8,10,7,6.0
4,2,165,8,Australia,Sri Lanka,1.3,0,0,Melbourne,Melbourne Cricket Ground,1,3,9,111,1,9,10,7,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50492,964,128,121,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,19,3,117,3,1,122,10,125,4.0
50493,964,128,122,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,19,4,118,2,1,123,10,125,3.0
50494,964,128,123,Sri Lanka,Australia,19.5,0,1,Colombo,R Premadasa Stadium,19,5,119,1,1,124,9,125,2.0
50495,964,128,124,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,19,6,120,0,1,125,10,127,3.0
50496,964,128,125,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,19,7,121,0,1,126,10,128,4.0

In [78]:
final_df.columns

Index(['match_id', 'runs_x', 'Unnamed: 0', 'batting_team', 'bowling_team',
       'ball', 'runs_y', 'player_dismissed', 'city', 'venue', 'over',
       'ball_no', 'ball_bowled', 'balls_left', 'player_dismissed_flag',
       'cumulative_dismissals', 'wicket_left', 'current_score', 'last_five'],
      dtype='object')

In [80]:
print(df.columns)

Index(['Unnamed: 0', 'match_id', 'batting_team', 'bowling_team', 'ball',
       'runs', 'player_dismissed', 'city', 'venue', 'over', 'ball_no',
       'ball_bowled', 'balls_left', 'player_dismissed_flag',
       'cumulative_dismissals', 'wicket_left', 'current_score', 'last_five'],
      dtype='object')

In [82]:
df['over'] = pd.to_numeric(df['over'], errors='coerce')
df['balls_left'] = pd.to_numeric(df['balls_left'], errors='coerce')

C:\Users\SANTHU\AppData\Local\Temp\ipykernel_2452\3558792542.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['over'] = pd.to_numeric(df['over'], errors='coerce')
C:\Users\SANTHU\AppData\Local\Temp\ipykernel_2452\3558792542.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left'] = pd.to_numeric(df['balls_left'], errors='coerce')

In [84]:
print(df[['over', 'balls_left']].head())

   over  balls_left
4     0         115
5     0         114
6     1         113
7     1         112
8     1         111

In [85]:
# Ensure that 'balls_left' is within a valid range (0 to 5)
df['balls_left'] = df['balls_left'].apply(lambda x: min(x, 5))

# Now calculate 'balls_faced' correctly
df['balls_faced'] = (df['over'] * 6) - df['balls_left']

C:\Users\SANTHU\AppData\Local\Temp\ipykernel_2452\2479814318.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left'] = df['balls_left'].apply(lambda x: min(x, 5))
C:\Users\SANTHU\AppData\Local\Temp\ipykernel_2452\2479814318.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_faced'] = (df['over'] * 6) - df['balls_left']

In [86]:
df['balls_faced'].fillna(0, inplace=True)

C:\Users\SANTHU\AppData\Local\Temp\ipykernel_2452\2010811131.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['balls_faced'].fillna(0, inplace=True)
C:\Users\SANTHU\AppData\Local\Temp\ipykernel_2452\2010811131.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_faced'].fillna(0, inplace=True)

In [88]:
# Correct the over and balls_left columns if needed
df['balls_left'] = df['balls_left'].apply(lambda x: min(x, 6))

# Calculate balls faced
df['balls_faced'] = (df['over'] * 6) + (6 - df['balls_left'])

# Fill missing values (if any)
df['balls_faced'].fillna(0, inplace=True)

C:\Users\SANTHU\AppData\Local\Temp\ipykernel_2452\1898736817.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left'] = df['balls_left'].apply(lambda x: min(x, 6))
C:\Users\SANTHU\AppData\Local\Temp\ipykernel_2452\1898736817.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_faced'] = (df['over'] * 6) + (6 - df['balls_left'])
C:\Users\SANTHU\AppData\Local\Temp\ipykernel_2452\1898736817.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['balls_faced'].fillna(0, inplace=True)
C:\Users\SANTHU\AppData\Local\Temp\ipykernel_2452\1898736817.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_faced'].fillna(0, inplace=True)

In [90]:
print(final_df.columns)

Index(['match_id', 'runs_x', 'Unnamed: 0', 'batting_team', 'bowling_team',
       'ball', 'runs_y', 'player_dismissed', 'city', 'venue', 'over',
       'ball_no', 'ball_bowled', 'balls_left', 'player_dismissed_flag',
       'cumulative_dismissals', 'wicket_left', 'current_score', 'last_five'],
      dtype='object')

In [93]:
print(df.columns)

Index(['Unnamed: 0', 'match_id', 'batting_team', 'bowling_team', 'ball',
       'runs', 'player_dismissed', 'city', 'venue', 'over', 'ball_no',
       'ball_bowled', 'balls_left', 'player_dismissed_flag',
       'cumulative_dismissals', 'wicket_left', 'current_score', 'last_five',
       'balls_faced'],
      dtype='object')

In [96]:
final_df = df[['batting_team', 'bowling_team', 'city', 'current_score', 'balls_left', 'wicket_left',
                'current_run_rate', 'last_five', 'runs']]

In [97]:
final_df.dropna(inplace=True)

C:\Users\SANTHU\AppData\Local\Temp\ipykernel_2452\2709626079.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.dropna(inplace=True)

In [98]:
final_df

,batting_team,bowling_team,city,current_score,balls_left,wicket_left,current_run_rate,last_five,runs
4,Australia,Sri Lanka,Melbourne,3,5,10,-0.000000,3.0,0
5,Australia,Sri Lanka,Melbourne,6,5,10,-12.857143,6.0,3
6,Australia,Sri Lanka,Melbourne,6,5,10,0.000000,6.0,0
7,Australia,Sri Lanka,Melbourne,7,5,10,2.727273,6.0,1
8,Australia,Sri Lanka,Melbourne,7,5,10,0.000000,4.0,0
...,...,...,...,...,...,...,...,...,...
63883,Sri Lanka,Australia,Colombo,125,3,10,0.053191,4.0,1
63884,Sri Lanka,Australia,Colombo,125,2,10,0.000000,3.0,0
63885,Sri Lanka,Australia,Colombo,125,1,9,0.000000,2.0,0
63886,Sri Lanka,Australia,Colombo,127,0,10,0.102041,3.0,2
63887,Sri Lanka,Australia,Colombo,128,0,10,0.050761,4.0,1

In [99]:
final_df.isnull().sum()

batting_team        0
bowling_team        0
city                0
current_score       0
balls_left          0
wicket_left         0
current_run_rate    0
last_five           0
runs                0
dtype: int64

In [100]:
final_df.shape

(50497, 9)

In [101]:
final_df = final_df.sample(final_df.shape[0])

In [102]:
final_df.shape

(50497, 9)

In [104]:
X = final_df.drop(columns=['runs'])
y = final_df['runs']

In [105]:
from sklearn.model_selection import train_test_split

In [106]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [107]:
X_train

,batting_team,bowling_team,city,current_score,balls_left,wicket_left,current_run_rate,last_five
35272,Pakistan,Australia,St Lucia,142,5,10,0.260304,21.0
29534,New Zealand,Pakistan,London,39,5,10,0.000000,2.0
36534,Sri Lanka,India,Chandigarh,18,5,10,0.000000,4.0
55800,England,South Africa,Cape Town,73,5,10,0.115385,3.0
9586,South Africa,Pakistan,Cape Town,155,5,10,0.292683,13.0
...,...,...,...,...,...,...,...,...
46735,New Zealand,England,Hamilton,75,5,10,0.000000,5.0
48243,South Africa,Sri Lanka,Colombo,1,5,10,-0.000000,5.0
48131,Sri Lanka,Bangladesh,Pallekele,35,5,10,1.132075,4.0
56201,South Africa,Bangladesh,Mirpur,121,5,10,0.075377,7.0
40112,India,England,Kolkata,5,5,10,0.000000,0.0

In [ ]:
from gettext import install
import pip
import xgboost


pip install xgboost

Requirement already satisfied: xgboost in c:\users\santhu\desktop\cricket_score_predictor-main\venv\lib\site-packages (3.0.0)
Requirement already satisfied: numpy in c:\users\santhu\desktop\cricket_score_predictor-main\venv\lib\site-packages (from xgboost) (2.2.5)
Requirement already satisfied: scipy in c:\users\santhu\desktop\cricket_score_predictor-main\venv\lib\site-packages (from xgboost) (1.15.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [110]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error

In [112]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer([
    ('transformer', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'city'])
], remainder='passthrough')

In [113]:
pipe = Pipeline(steps=[
    ('step1', transformer),
    ('step2', StandardScaler()),
    ('step3', XGBRegressor(n_estimators=1000, learning_rate=0.2, max_depth=12, random_state=1))
])

In [114]:
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)

In [115]:
r2_score(y_test, y_pred)

0.9490086436271667

In [116]:
mean_absolute_error(y_test, y_pred)

0.11858165264129639

In [117]:
import pickle
pickle.dump(pipe, open('pipe.pkl', 'wb'))

In [121]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression

categorical_cols = ['batting_team', 'bowling_team', 'city']
numerical_cols = ['current_score', 'balls_left', 'wicket_left', 'current_run_rate', 'last_five']

preprocessor = ColumnTransformer([
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
], remainder='passthrough')

pipe = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])

# Train the model on training data (X_train, y_train)
pipe.fit(X_train, y_train)

# Save it
import pickle
pickle.dump(pipe, open('pipe.pkl', 'wb'))

In [122]:
# Your imports, preprocessor, pipe setup...
pipe.fit(X_train, y_train)
pickle.dump(pipe, open('pipe.pkl', 'wb'))

In [123]:
import pickle
pipe = pickle.load(open('pipe.pkl', 'rb'))